# Jekyll configuration

name: cec-net-au
description: Rob Bennet's Central Eyre Communications website
author:
  name: Mike Causer
  email: mcauser@gmail.com

url: http://central-eyre-communications.github.io/cec-net-au

exclude: [".ruby-version", "Gemfile", "Gemfile.lock", "README.md"]

sass:
  style: compressed

encoding: utf-8
